name: 'Pull GH Sponsors'

on:
  push:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  get-sponsors:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --ignore-engines

      - name: Get GH sponsors
        id: gh-sponsors
        run: |
          mkdir tmp

          curl \
          -X POST \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d "$(node scripts/graphql-to-json.js scripts/sponsors.gql)" \
          https://api.github.com/graphql \
          > tmp/sponsors.json

      - run: |
          node scripts/add-geocode.js
        env:
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}

      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "Pine Wu"
            git config user.email octref@gmail.com
            git status
            git add -A
            git commit -m "(//Ï‰//)"
            git push
          else
            echo "no changes"
          fi

      - run: yarn build

      - uses: actions/checkout@v2
        with:
          repository: octref/matsu
          token: ${{ secrets.GH_KEY }}
          path: tmp/matsu

      - run: |
          [ ! -d tmp/matsu/dist ] && mkdir tmp/matsu/dist
          cp dist/*.js tmp/matsu/dist/
          cp index.html tmp/matsu/sponsors.html

      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "Pine Wu"
            git config user.email octref@gmail.com
            git status
            git add -A
            git commit -m "update sponsors"
            git push
          else
            echo "no changes"
          fi
        working-directory: tmp/matsu
